// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv2LqQzYaAkp5z65V8Bs4K_QubeCGoY0E',
    appId: '1:58056088677:web:a5287d9049d4cf6618ba8c',
    messagingSenderId: '58056088677',
    projectId: 'grekos-4ab63',
    authDomain: 'grekos-4ab63.firebaseapp.com',
    storageBucket: 'grekos-4ab63.firebasestorage.app',
    measurementId: 'G-XJ4RZEZV63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTDFHdEHVk7Nui-Pj6B-D2KU6SzzbCtQ',
    appId: '1:58056088677:android:2b94391cf1dce8b818ba8c',
    messagingSenderId: '58056088677',
    projectId: 'grekos-4ab63',
    storageBucket: 'grekos-4ab63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mVwaznM9kjFO_6qAGR_ApuUTw4rrN18',
    appId: '1:58056088677:ios:39edb6728b913a6118ba8c',
    messagingSenderId: '58056088677',
    projectId: 'grekos-4ab63',
    storageBucket: 'grekos-4ab63.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mVwaznM9kjFO_6qAGR_ApuUTw4rrN18',
    appId: '1:58056088677:ios:39edb6728b913a6118ba8c',
    messagingSenderId: '58056088677',
    projectId: 'grekos-4ab63',
    storageBucket: 'grekos-4ab63.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv2LqQzYaAkp5z65V8Bs4K_QubeCGoY0E',
    appId: '1:58056088677:web:4f495123e967028f18ba8c',
    messagingSenderId: '58056088677',
    projectId: 'grekos-4ab63',
    authDomain: 'grekos-4ab63.firebaseapp.com',
    storageBucket: 'grekos-4ab63.firebasestorage.app',
    measurementId: 'G-4G4Q0FGMZG',
  );

}